/*
 * generated by Xtext 2.20.0
 */
package org.xtext.thphr16


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathCompilerRuntimeModule extends AbstractMathCompilerRuntimeModule {
}
